### PR TITLE
Support PHPUnit 8

### PR DESCRIPTION
**Pull request by martinssipenko**

### CODE REVIEW

**Comment by martin-helmich** [comment]
Hey, thanks for this contribution! :+1: I'll give it a detailed look ASAP.

Just a quick question: From the `README` it looks like a new major semver bump is required for this to work with PHPUnit 8; correct?

**Comment by martinssipenko** [comment]
Correct, phpunit has removed construct on Constraint class. I aslo email you today to chat about why I think phpunit could be moved to dev require, let me know if you are able to jump on a wuick call ir somewhere in chat room.

**Comment by martinssipenko** [comment]
@martin-helmich any updates on this?

**Comment by mathieu-bour** [comment]
Also highly interested!

**Pull request merged**
